### ISSUE TITLE
Cleared amount always equal to 100

### ISSUE THREAD

**Issue by tameroski** [sebastianwachter/wc-scratch#74]
Hi,

I'm trying to use this web component in a Vue 3 component, but the `percentage-update` event always return '100'. Any idea about the reason why ?

Thanks 

```vue
<template>
  <div class="col-12">
    <div id="scratchCardWrapper">
      <wc-scratch brush-size="40" percentage-update="true" @percentage-update="onComplete">
        <div class="scratchCardContainer" :style="{width: cardWidth + 'px', height: cardHeight + 'px'}">
          Some HTML with Vue logic
          <img :src="urlImage"/>
        </div>
      </wc-scratch>
    </div>
  </div>
</template>
<script>
import "wc-scratch";
import { mapGetters } from "vuex";
export default {
  computed: {
    ...mapGetters(["currentJeu"]),
    urlImage() {
      return `${process.env.VUE_APP_API_URL}/api/upload/${this.currentJeu.Visuel}`;
    },
  },
  methods: {
    onComplete(percentage) {
      console.log("COMPLETE", percentage.detail);
    },
  },
  created() {
    let windowWidth = window.innerWidth;
    this.cardWidth = windowWidth > 768 ? 728 : windowWidth - 40;
    this.cardHeight = windowWidth >= 768 ? 542 : 340;
  },
};
</script>
```

Console output : 

COMPLETE 0
COMPLETE 100
COMPLETE 100
COMPLETE 100
COMPLETE 100
...

The canvas size seams to be correctly set : 
```
<canvas width="728" height="542" style="width: 728px; height: 542px;"></canvas>
```

**Comment by sebastianwachter** [comment]
Very interesting 😄 - I can reproduce this and I'm taking a look into it

**Comment by sebastianwachter** [comment]
@tameroski can you confirm that if you set the `scratch-color` parameter to a colour that is not `#000000` it works? 

(It's still a bug but I want to see if our both situations result in the same outcome)

**Comment by tameroski** [comment]
I confirm it does work 👍

**Comment by tameroski** [comment]
It does work. Depends on the color, though : #FF00FF works, but not #FF00FF. Weird bug 😅

**Comment by sebastianwachter** [comment]
Oof I see it gets weirder I will dig more into it tomorrow but I think I have an idea 👀

**Comment by tameroski** [comment]
It works now, thanks !
